BOT_TOKEN = "************************"
YANDEX_GPT_API_KEY="**********************"
YANDEX_FOLDER_ID = "**********"
DATABASE_URL_LOCAL = "postgresql+asyncpg://user:password@localhost:5432/"
DATABASE_URL = "postgresql+asyncpg://user:password@***.mdb.yandexcloud.net:6432/"
DATABASE_NAME = "tgbot"
DEFAULT_DATABASE_NAME = "tgbot"
