# docker-compose up -d --build
# docker-compose down

# Для linux ubuntu
# sudo docker compose up -d --build

version: '3.9'

services:
  bot:
    build: .
    restart: always
    volumes:
      - ./config.py:/app/config.py
    environment:
      - PYTHONUNBUFFERED=1
